version: 1

resources:
  sw_planets:
    cache_duration: 5s
    source:
      kind: http
      config:
        method: get
        path: https://swapi.dev/api/planets

  sw_people:
    cache_duration: 10s
    source:
      kind: http
      config:
        method: get
        path: https://swapi.dev/api/people

routes:
  - path: /v1/sw
    method: GET
    resources:
      sw_planets:
        as: planets
      sw_people:
        as: people