version: 1

globals:
  sw_url: "https://swapi.dev/api"

resources:
  sw_planets:
    source:
      kind: http
      config:
        method: get
        path: {{sw_url}}/planets

  sw_people:
    source:
      kind: http
      config:
        method: get
        path: https://swapi.dev/api/people

routes:
  - path: /v1/sw
    method: GET
    resources:
      sw_planets:
        async: true
      sw_people:
        async: true